//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LawCMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbLawCMSEntities : DbContext
    {
        public dbLawCMSEntities()
            : base("name=dbLawCMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<tbl_Case> tbl_Case { get; set; }
        public virtual DbSet<tbl_Case_Attachments> tbl_Case_Attachments { get; set; }
        public virtual DbSet<tbl_Case_Notes> tbl_Case_Notes { get; set; }
        public virtual DbSet<tbl_Client> tbl_Client { get; set; }
        public virtual DbSet<tbl_Role> tbl_Role { get; set; }
        public virtual DbSet<tbl_Type_Of_Matter> tbl_Type_Of_Matter { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
    }
}
