//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LawCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        public string User_Name { get; set; }
        public string Password { get; set; }
        public Nullable<int> Role_ID { get; set; }
        public Nullable<bool> is_Active { get; set; }
    }
}
