//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LawCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Type_Of_Matter
    {
        public int Type_Of_Matter_ID { get; set; }
        public string Type_Of_Matter { get; set; }
        public Nullable<bool> is_Active { get; set; }
    }
}
