//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LawCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Case_Attachments
    {
        public int Attachment_ID { get; set; }
        public Nullable<int> Case_ID { get; set; }
        public string Case_Attachment { get; set; }
    }
}
