//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LawCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Client
    {
        public int Client_ID { get; set; }
        public string User_ID { get; set; }
        public string Title { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Home_Address { get; set; }
        public string Work_Address { get; set; }
        public string Next_Of_Kin_Last_Name { get; set; }
        public string Next_Of_Kin_First_Name { get; set; }
        public string Next_Of_Kin_Address { get; set; }
        public string Next_Of_Kin_Phone { get; set; }
        public string Next_Of_Kin_Email { get; set; }
        public string Next_Of_Kin_Fax { get; set; }
        public string Notes { get; set; }
    }
}
